# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'second.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setStyleSheet("background-color: rgb(228, 189, 255);\n"
"background-color: rgb(185, 183, 255);")
        self.addButton = QtWidgets.QPushButton(Dialog)
        self.addButton.setGeometry(QtCore.QRect(140, 210, 113, 32))
        self.addButton.setObjectName("addButton")
        self.num1 = QtWidgets.QLineEdit(Dialog)
        self.num1.setGeometry(QtCore.QRect(60, 140, 113, 21))
        self.num1.setStyleSheet("color: rgb(10, 10, 10);")
        self.num1.setObjectName("num1")
        self.num2 = QtWidgets.QLineEdit(Dialog)
        self.num2.setGeometry(QtCore.QRect(220, 140, 113, 21))
        self.num2.setStyleSheet("color: rgb(6, 6, 6);")
        self.num2.setObjectName("num2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(160, 80, 60, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.addButton.setText(_translate("Dialog", "add"))
        self.label.setText(_translate("Dialog", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
