# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogFirst.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(483, 367)
        Dialog.setStyleSheet("background-color: rgb(255, 201, 214);")
        self.pressMeButton = QtWidgets.QPushButton(Dialog)
        self.pressMeButton.setGeometry(QtCore.QRect(300, 160, 113, 32))
        self.pressMeButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pressMeButton.setStyleSheet("background-color: rgb(130, 135, 139);\n"
"font: 18pt \"Rockwell\";")
        self.pressMeButton.setObjectName("pressMeButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(170, 80, 151, 41))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 18pt \".AppleSystemUIFont\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.helloButton = QtWidgets.QPushButton(Dialog)
        self.helloButton.setGeometry(QtCore.QRect(70, 160, 113, 32))
        self.helloButton.setStyleSheet("background-color: rgb(130, 135, 139);\n"
"font: 75 18pt \"Noteworthy\";")
        self.helloButton.setObjectName("helloButton")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 220, 60, 16))
        self.label_2.setObjectName("label_2")
        self.pic = QtWidgets.QLabel(Dialog)
        self.pic.setGeometry(QtCore.QRect(10, 10, 101, 121))
        self.pic.setText("")
        self.pic.setPixmap(QtGui.QPixmap("blueflower.webp"))
        self.pic.setScaledContents(True)
        self.pic.setObjectName("pic")
        self.radioButton = QtWidgets.QRadioButton(Dialog)
        self.radioButton.setGeometry(QtCore.QRect(270, 20, 100, 20))
        self.radioButton.setAutoExclusive(False)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_2.setGeometry(QtCore.QRect(270, 50, 100, 20))
        self.radioButton_2.setAutoExclusive(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_3.setGeometry(QtCore.QRect(280, 230, 100, 20))
        self.radioButton_3.setAutoExclusive(False)
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_4.setGeometry(QtCore.QRect(280, 260, 100, 20))
        self.radioButton_4.setAutoExclusive(False)
        self.radioButton_4.setObjectName("radioButton_4")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(140, 30, 104, 26))
        self.comboBox.setObjectName("comboBox")
        self.horizontalSlider = QtWidgets.QSlider(Dialog)
        self.horizontalSlider.setGeometry(QtCore.QRect(60, 260, 160, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(190, 120, 118, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "hwa"))
        self.pressMeButton.setText(_translate("Dialog", "press me"))
        self.label.setText(_translate("Dialog", "please enter value"))
        self.helloButton.setText(_translate("Dialog", "hello"))
        self.label_2.setText(_translate("Dialog", "TextLabel"))
        self.radioButton.setText(_translate("Dialog", "RadioButton"))
        self.radioButton_2.setText(_translate("Dialog", "RadioButton"))
        self.radioButton_3.setText(_translate("Dialog", "RadioButton"))
        self.radioButton_4.setText(_translate("Dialog", "RadioButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
